### PR TITLE
EOY 2015 ensure we can still scroll-y

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
So we noticed in two of our tests, I broke the vertical scroll. This fixes it.

**Comment by ScottDowne** [comment]
This issues is I had to add elements to the fox animation, which caused a horizontal scrollbar. To fix that, I hid the overflow(removed the scrollbar), but didn't cross my mind at the time that it would also hide the vertical scrollbar, which was not my intent.

My fix ensures only the horizontal scrollbar is hidden.

**Comment by ScottDowne** [comment]
To see the bug in action, go here: https://snippets.mozilla.com/show/5508/

And shorten your window height a bit until something gets cut off. You don't see a scrollbar as expected.

**Comment by ScottDowne** [comment]
@schalkneethling review? thoughts?

**Comment by ScottDowne** [comment]
@schalkneethling 

I noticed a few other not great situations when the screen's width gets smaller. I created a separate patch for that though because it was larger than this one, and probably not as critical.

You can find it here: https://github.com/mozilla/snippets/pull/76

**Comment by Osmose** [comment]
r+, merged to fix the issue, but I think in the long term any CSS that messes with the body should be _very_ conservative about things like hiding scrollbars.

**Pull request merged**
