### PR TITLE
EOY 2015 three varied spectacular snippets

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@glogiotatidis Trying to get these to you as soon as possible so you can have some time to take a closer look.

There might be a few small changes to come, but because of time zones I didn't want to waste any time and would rather you take a look at the bulk of it now.

They should look and work like these demos:
http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-1/
http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-2/
http://scottdowne.github.io/eoy-snippets/2015-spectacular-snippet-3/

I also created #71 but decided another pull request made more sense as it's not as much of a priority, so it kept this patch a bit smaller.

Thoughts?

**Comment by glogiotatidis** [comment]
CCing @schalkneethling for review

**Comment by glogiotatidis** [comment]
If there are no other review comments I'm good to merge these and bring them to production. 

@ScottDowne thanks for pull requesting those sooner than later. I'd appreciate efforts to limit last minute changes as much as possible for increasingly less stress towards holidays :christmas_tree:   :)

Thanks!

**Comment by schalkneethling** [comment]
This looks good to me r+

**Comment by ScottDowne** [comment]
@glogiotatidis @schalkneethling 

When do we think this goes to production?

**Comment by ScottDowne** [comment]
Added a few small updates in a new commit from feedback I had. I can merge these commits if it's easier.

**Comment by glogiotatidis** [comment]
Merged here: https://github.com/mozilla/snippets/commit/c4f16d0a71aa1dc3ea07b6be2dcee323fdecbf10

Thanks @ScottDowne :christmas_tree:

**Comment by glogiotatidis** [comment]
And thanks for @schalkneethling too of course :santa:

**Pull request closed without merging**
