### PR TITLE
mass surveillance snippet

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1152133

**Comment by glogiotatidis** [comment]
Thanks for the pull request @ScottDowne. This looks good :) 

Due to time constrains I did some minor changes to your code and merged in. I hope you're OK with that:

 - Set variables for text and default value for eye_color https://github.com/mozilla/snippets/commit/83ef9d95a2f6e3a88915dc2978d98ea39e754a6b
 - Remove this unused line. https://github.com/mozilla/snippets/commit/1456f41179919c57ac41b73013607b71b4e33ce4

**Comment by glogiotatidis** [comment]
BTW two things to note: 
 1. snippets need to be xml valid, so I replaced `&nbsp;` with it's numerical representation `&#160;`
 2. Preview adds some spacing between the form and the snippet, but real about:home doesn't. I removed your `-15px` margin and fixed the template now. Thanks for pointing that out. https://github.com/mozilla/snippets/commit/83ef9d95a2f6e3a88915dc2978d98ea39e754a6b#diff-b3aac33791e1955fe993d14634279eebL26 https://github.com/mozilla/snippets-service/commit/4133b392b8509f9fa8dccc496a1b188a1ac8d368

**Comment by ScottDowne** [comment]
Very cool! Thanks for the help!

**Pull request merged**
