### PR TITLE
Add language as a template field for Basket email

### PR DESCRIPTION
**Pull request by ckprice**
TODO: somehow use data-locale to do this

@Osmose could you give this a once over with Giorgos out? Note: the template has already been updated on stage/prod.

### CODE REVIEW

**Comment by Osmose** [comment]
One question: Is the problem here that "set of language codes that can be sent to basket" is not the same as "set of locale codes used on the snippet element"?

If the answer is yes, then r+ to this as a temporary measure until a better method of mapping can be found. Otherwise I don't see why `lang` is a separate value.

**Comment by Osmose** [comment]
If basket just takes two-letter codes, maybe `locale.substr(0, 2)` would suffice. Or if you're worried about being able to preview it, maybe add `data-locale` to the preview template? https://github.com/mozilla/snippets-service/blob/master/snippets/base/templates/base/preview.html#L31

**Comment by ckprice** [comment]
> If the answer is yes, then r+ to this as a temporary measure until a better method of mapping can be found. Otherwise I don't see why lang is a separate value.

Per IRC I'd like the ability for an admin to be able to confirm the language of the email they are receiving through preview. Otherwise they wouldn't be able to test the snippet fully.

(please merge when able)

**Comment by Osmose** [comment]
Merged in d1b5ffb

**Pull request closed without merging**
