### PR TITLE
Update simple snippet

### PR DESCRIPTION
**Pull request by glogiotatidis**
Changes in simple snippet and logo swap snippet with close button, to make the button appear over the text as designed here https://bugzilla.mozilla.org/show_bug.cgi?id=1172579#c15

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1172579#c31 point 1

@schalkneethling r?

### CODE REVIEW

**Comment by schalkneethling** [comment]
@glogiotatidis I had a look over the general code of the snippet and have a couple of suggestions.

First a small change to the HTML:

```
  {% if blockable or clickable %}
    <div id="block-snippet-overlay-{{ snippet_id }}" class="block-snippet-overlay-{{ snippet_id }}">
  {% endif %}
    <a href="{{ icon_url|safe }}">
      <img class="icon" src="{{ icon }}" />
    </a>
    <p>{{ text|safe }}</p>
  {% if blockable or clickable %}
    </div>
  {% endif %}
```
Next update the following to rules to reflect the below:

```
.block-snippet-overlay-{{ snippet_id }} {
    padding: 5px 10px;
    width: 100%;
    height: 100%;
    border-radius: 12px;
}

xbutton-{{ snippet_id }} {
    position: absolute;
    top: 5px;
    right: -20px;
    background-image: url(…);
    background-repeat: no-repeat;
    background-size: 28px 28px;
    background-color: transparent;
    border: 0;
    width: 28px;
    height: 28px;
    visibility: hidden;
    z-index: 10;
}
```
Remove this rule (I believe this resides somewhere other than in this snippet template itself)

```
#snippetContainer div.snippet img.icon
```
Update the below two rules to be as follows (I believe this also resides somewhere other than in this snippet template):

```
.snippet p {
    display: inline-block;
}

.snippet .icon {
    display: inline-block;
    height: 50px;
    vertical-align: bottom;
}
```
Let me know your thoughts.

**Comment by schalkneethling** [comment]
Following on from IRC, change #snippetContainer div.snippet img.icon to be:

```
#snippetContainer div.snippet img.icon {
    float: none;
    margin: 0;
}
```

Change .snippet .icon to be:

```
.snippet .icon {
    position: relative;
    right: 0;
    top: 0;
    display: inline-block;
    height: 50px;
    vertical-align: bottom;
}
```
and lastly .snippet p to:

```
.snippet p {
display: inline-block;
padding-left: 0;
width: auto;
height: auto;
vertical-align: inherit;
}
```

**Comment by glogiotatidis** [comment]
Added an  missing `{{ snippet_id }}` in the last commit.https://github.com/glogiotatidis/snippets/commit/d6802dfbf5cd63ac0080e2650743b18a41ee89de#diff-b370f285ff5f2359e385888175c6f25fR41

**Comment by schalkneethling** [comment]
For easy reference https://gist.github.com/schalkneethling/55ac2fc47b5972bd4ef8

**Comment by schalkneethling** [comment]
Only one more tweak needed:

```
.snippet p {
    display: inline-block;
    padding-left: 0;
    width: auto;
    max-width: 380px;
    height: auto;
    vertical-align: inherit;
}
```

**Comment by glogiotatidis** [comment]
Thanks @schalkneethling

**Pull request merged**
