### PR TITLE
[fix bug 1115229] Hide menu on window resize (ref bug 1091785)

### PR DESCRIPTION
**Pull request by ckprice**
@Osmose added an additional event listener per Alex's comment in IRC.

### CODE REVIEW

**Comment by Osmose** [comment]
@alexgibson r?

**Comment by alexgibson** [comment]
This will fire a lot of events - maybe better only to add a one-time `resize` listener when the hello panel is open?

**Comment by alexgibson** [comment]
LGTM, r+

**Comment by alexgibson** [comment]
Oh, hang on - probably want to make sure your click event gets tidied up as well?

If so, make sure to `removeEventListener` for both `click` and `resize` when the panel gets hidden

**Comment by ckprice** [comment]
@alexgibson r?

**Comment by alexgibson** [comment]
Tidy! r+

**Pull request merged**
