### PR TITLE
[bug 1225987] Create Mobile Snippet with 200px Icon

### PR DESCRIPTION
**Pull request by ckprice**
@glogiotatidis r?

Note this is based on #68 with `blockable`, except with a 200px wide icon. I had trouble getting this absolute positioned snippet to work with a variable wide icon.

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@schalkneethling do you have time to r?

**Comment by schalkneethling** [comment]
Hmmmm, the changed file is not viewable in the PR and I cannot comment on it on your fork @ckprice - weird

**Comment by ckprice** [comment]
@schalkneethling hmmm let me see if I can do anything to fix it. It's basically a duplicate of #68, with a wider icon.

**Comment by schalkneethling** [comment]
@ckprice yeah, I saw when I looked at the file on your fork. There are some of the same simple CSS nits and issues here so, if #68 is sorted out, I reckon this one will be good to go as well. So, perhaps focus on #68 ?

**Comment by ckprice** [comment]
@schalkneethling yes please!

**Comment by ckprice** [comment]
Addressed comments from #68.

This PR is identical to #68, except for [lines 39 and 40](https://github.com/ckprice/snippets/blob/c826b6421ada2b8b46f60a0f636c290e89e79897/campaigns/mobile/mobile-snippet-widget-200.html#L39).

**Comment by schalkneethling** [comment]
r+ :iphone:

**Comment by glogiotatidis** [comment]
Squashed and merged, thanks folks!

**Comment by glogiotatidis** [comment]
Commit: https://github.com/mozilla/snippets/commit/b4faedda67eeb436e878bec2bdd455314ab1eb32

Also updated on production.

**Pull request closed without merging**
