### PR TITLE
[bug 1206861] PB Video (3of3)

### PR DESCRIPTION
**Pull request by ckprice**
This is snippet 3 of 3 for Private Browsing. See bug for full specs.

Stage: https://snippets.allizom.org/admin/base/snippet/97/

@glogiotatidis r? Also, is there some kind of throttling with the video assets? Seems like every 10 minutes or so the video won't load for me. Any idea?

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Similar comments about `launch-pb` selectors, micro-optimization of loops

**Comment by glogiotatidis** [comment]
> Seems like every 10 minutes or so the video won't load for me.

Every 10 minutes? Did you mean tries / reloads?

Videos should get uploaded to the CDN (using `Uploaded files` on the admin) and there's no throttling afaik. Do you have a url I can check?

**Comment by glogiotatidis** [comment]
in gdocs I see that this is cancelled. Is that correct @ckprice ?

**Comment by ckprice** [comment]
Yes, sorry @glogiotatidis =/

**Pull request closed without merging**
