### PR TITLE
[bug 1225997] Fix some icon alignment and video alignment

### PR DESCRIPTION
**Pull request by ckprice**
Fix some minor icon and video alignment issues.

Also, what is the best way to get the three videos attached to the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1226356) uploaded to the Snippet CDN?

@glogiotatidis r?

Sample: https://snippets.allizom.org/show/85/

Here it is working on about:home using snippet switcher
http://cl.ly/image/3J1j3F2R2j1V
http://cl.ly/image/2z1Z0p14173C

### CODE REVIEW

**Comment by glogiotatidis** [comment]
wfm :key:

**Comment by glogiotatidis** [comment]
updated on prod

**Comment by ckprice** [comment]
Thanks @glogiotatidis !

Just one question - what's the best way to get the videos up to the snippet CDN? (we're waiting on a final version of the video)

**Comment by glogiotatidis** [comment]
> Just one question - what's the best way to get the videos up to the snippet CDN? (we're waiting on a final version of the video)

Through snippets /admin -> UploadFile

**Pull request merged**
