### PR TITLE
[fix bug 1163690] Pocket simple snippet

### PR DESCRIPTION
**Pull request by ckprice**
https://bugzilla.mozilla.org/show_bug.cgi?id=1163690

https://snippets.allizom.org/show/86/

@glogiotatidis r?

### CODE REVIEW

**Comment by glogiotatidis** [comment]
My only concern is that if user has removed the pocket icon from both the url bar and the drawer, clicking the link does nothing. Maybe we should alter the message based on `isTargetAvailable()`  value?

**Comment by ckprice** [comment]
@glogiotatidis hmm, is it possible for this to happen? I don't think a user can remove the icon completely. Since it's a snippet, we'll only be deploying to locales with the Pocket icon in the build.

**Comment by ckprice** [comment]
Actually, thinking more about this, I'm not sure there is a case where it would do nothing. Except for testing purposes where the `testingOrigins` about:config key hasn't been set.

**Comment by glogiotatidis** [comment]
Actually i've removed the pocket icon from both the url bar and the drawer. You can do this by clicking customize and dragging the icon outside the drawer into the "additional tools and features list" on the left. In this case the snippet does nothing.

I can see people doing this but i don't have numbers on how many. Since we have a way to test this I suggest that we do something, for example display a proper message. If you think otherwise I'll review as is.

**Comment by ckprice** [comment]
@glogiotatidis if I move this to the customization palette as you described, the click action changes to whatever the 'icon_url' the user has configured. In the case of the above sample, it is google.com.

This is not what you experience?

**Comment by glogiotatidis** [comment]
* Changed `icon_url` to `fallback_url`
* Yes I can see the redirect. The reason it didn't work for me before was that I was testing it in the preview mode. Works fine now.

Thanks @ckprice, you rock! :metal:

**Comment by ckprice** [comment]
No, @glogiotatidis, YOU rock!

**Pull request merged**
